#!/usr/bin/env bash
#
# Through the Cracks — Doppler Setup Wizard
# Generated by the /wizard skill.
#
# Walks you through:
#   1. Installing the Doppler CLI (via Homebrew)
#   2. Authenticating with Doppler (`doppler login`)
#   3. Creating/linking the `through-the-cracks` Doppler project
#   4. Syncing local .env secrets into Doppler
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

banner "Through the Cracks — Doppler Secrets Setup"

# ── Stage 1: Install Doppler CLI ──────────────────────────────────────────
stage "Install Doppler CLI"
say ""
if command -v doppler >/dev/null 2>&1; then
  printf '  %s✓ Doppler CLI is already installed%s\n' "$GREEN" "$RESET"
  doppler --version 2>/dev/null | head -1 | while read -r line; do note "$line"; done
  say ""
  pause "Press Enter to continue..."
else
  say "Doppler CLI manages secret injection across local dev and Docker."
  say "Installing via Homebrew..."
  say ""
  if command -v brew >/dev/null 2>&1; then
    step "Running: brew install dopplerhq/cli/doppler"
    brew install dopplerhq/cli/doppler 2>&1 | tail -5
    say ""
    if command -v doppler >/dev/null 2>&1; then
      printf '  %s✓ Doppler CLI installed successfully%s\n' "$GREEN" "$RESET"
    else
      warn "Doppler CLI installation complete. Restart terminal if binary not found."
    fi
  else
    say "Homebrew is not installed. You can install Doppler CLI manually:"
    open_url "https://docs.doppler.com/docs/install-cli"
    pause "Press Enter once Doppler CLI is installed..."
  fi
fi

# ── Stage 2: Login to Doppler ─────────────────────────────────────────────
stage "Authenticate with Doppler"
say ""
say "We will authenticate the Doppler CLI with your Doppler account."
say ""

if doppler me >/dev/null 2>&1; then
  printf '  %s✓ Already authenticated with Doppler%s\n' "$GREEN" "$RESET"
else
  step "Opening browser for Doppler login..."
  doppler login --scope .
fi

say ""
pause "Press Enter to continue..."

# ── Stage 3: Setup/Link Doppler Project ───────────────────────────────────
stage "Setup or Link Doppler Project"
say ""
say "Linking local directory to Doppler project 'through-the-cracks'..."
say ""

open_url "https://dashboard.doppler.com/workplaces/projects"
step "Ensure you have created a project named 'through-the-cracks' in Doppler."
step "We will now run 'doppler setup' to select the project and environment (dev)."
say ""

doppler setup --project through-the-cracks --config dev 2>&1 || {
  warn "Manual setup required. Run: doppler setup"
}

say ""
pause "Press Enter to continue..."

# ── Stage 4: Sync Secrets from .env to Doppler ────────────────────────────
stage "Sync Secrets to Doppler"
say ""
say "We will now push your current .env secrets into Doppler so they"
say "are stored securely in the cloud."
say ""

if [[ -f .env ]]; then
  step "Uploading .env secrets to Doppler..."
  doppler secrets upload .env 2>&1 || {
    warn "Failed auto upload. You can manually upload via: doppler secrets upload .env"
  }
  printf '  %s✓ Secrets synced to Doppler!%s\n' "$GREEN" "$RESET"
else
  warn "No .env file found to sync."
fi

say ""
note "From now on, you can run commands with Doppler secret injection:"
note "  doppler run -- node scripts/ingest.js"
note "  doppler run -- docker-compose up"
say ""
pause "Press Enter to finish..."

# ──────────────────────────────────────────────────────────────────────────

finish
