#!/usr/bin/env bash
#
# Through the Cracks — GCP Billing Setup Wizard
# Generated by the /wizard skill.
#
# Walks you through:
#   1. Creating a Billing Account
#   2. Linking it to your project
#   3. Setting up a $0 budget alert
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

banner "Through the Cracks — GCP Billing Setup"

# ── Stage 1: Add a Billing Account ────────────────────────────────────────
stage "Create a Billing Account"
say ""
say "Google Cloud requires a billing account to unlock features like Cloud Functions"
say "and scheduled jobs, even if you never exceed the free tier."
say "You'll need to enter a credit card, but you won't be charged unless you manually"
say "upgrade a service past the free limits."
say ""
open_url "https://console.cloud.google.com/billing/create"
say ""
step "Follow the prompts to create a new billing account."
step "Select your country and agree to the terms."
step "Enter your payment information."
step "Click 'Start my free trial' or 'Submit and enable billing'."
say ""
pause "Press Enter once your billing account is created..."

# ── Stage 2: Link Project to Billing Account ──────────────────────────────
stage "Link Project to Billing Account"
say ""
say "Now we need to make sure your 'through-the-cracks' project is linked"
say "to the billing account you just created."
say ""
open_url "https://console.cloud.google.com/billing/projects"
say ""
step "Find your project (e.g., 'through-the-cracks') in the list."
step "Under the 'Billing account' column, click the three dots (...)"
step "Select 'Change billing account'."
step "Choose the billing account you just created and click 'Set account'."
say ""
note "If it already shows your billing account, you're good to go!"
say ""
pause "Press Enter once your project is linked..."

# ── Stage 3: Set up a Budget Alert ────────────────────────────────────────
stage "Set up a Budget Alert"
say ""
say "To ensure you never get surprise charges, we'll set up an alert."
say "Note: Budget alerts don't automatically turn off services (that requires"
say "complex scripting), but they will email you instantly if costs > \$0."
say ""
open_url "https://console.cloud.google.com/billing/budgets"
say ""
step "Click '+ CREATE BUDGET'."
step "Name the budget something like 'Zero Cost Alert'."
step "Make sure your project ('through-the-cracks') is selected."
step "Click 'Next'."
step "Under 'Budget type', select 'Specified amount'."
step "Enter a Target amount of \$1.00 (Google doesn't always allow \$0.00)."
step "Click 'Next'."
step "Under 'Alert rules', you'll see percentages (e.g., 50%, 90%, 100%)."
step "You can leave these as default. If costs hit \$0.50, you get an email."
step "Click 'Finish' or 'Save'."
say ""
pause "Press Enter once your budget alert is saved..."

# ──────────────────────────────────────────────────────────────────────────

finish
