#!/usr/bin/env bash
#
# Through the Cracks — BigQuery Setup Wizard
# Generated by the /wizard skill.
#
# Walks you through:
#   1. Installing the gcloud CLI (if needed)
#   2. Authenticating with Google Cloud
#   3. Enabling the BigQuery API
#   4. Creating the dataset and tables
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current: %s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$current" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "Through the Cracks — BigQuery Setup"

# ── Stage 1: Install gcloud CLI ───────────────────────────────────────────
stage "Install Google Cloud CLI"
say ""
if command -v gcloud >/dev/null 2>&1; then
  printf '  %s✓ gcloud CLI is already installed%s\n' "$GREEN" "$RESET"
  gcloud --version 2>/dev/null | head -1 | while read -r line; do note "$line"; done
  say ""
  pause "Press Enter to continue..."
else
  say "The gcloud CLI is required for BigQuery authentication."
  say "We'll install it now via Homebrew (macOS)."
  say ""
  if command -v brew >/dev/null 2>&1; then
    if confirm "Install gcloud CLI via Homebrew?"; then
      say ""
      step "Installing google-cloud-sdk..."
      brew install --cask google-cloud-sdk 2>&1 | tail -5
      say ""
      # Source the shell completion
      if [[ -f "$(brew --prefix)/share/google-cloud-sdk/path.bash.inc" ]]; then
        source "$(brew --prefix)/share/google-cloud-sdk/path.bash.inc"
      fi
      if command -v gcloud >/dev/null 2>&1; then
        printf '  %s✓ gcloud CLI installed successfully%s\n' "$GREEN" "$RESET"
      else
        warn "gcloud may not be on your PATH yet."
        warn "You may need to restart your terminal, then re-run this wizard."
        say ""
        note "Or manually add to your shell profile:"
        note "  source \"\$(brew --prefix)/share/google-cloud-sdk/path.bash.inc\""
        pause "Press Enter after fixing your PATH (or Ctrl-C to exit and retry)..."
      fi
    else
      say ""
      say "You can also install manually from:"
      open_url "https://cloud.google.com/sdk/docs/install"
      pause "Press Enter once gcloud is installed..."
    fi
  else
    say "Homebrew is not installed. You can install gcloud manually:"
    open_url "https://cloud.google.com/sdk/docs/install"
    pause "Press Enter once gcloud is installed..."
  fi
fi

# ── Stage 2: Authenticate with gcloud ─────────────────────────────────────
stage "Authenticate with Google Cloud"
say ""
say "We need to authenticate gcloud with your Google account and set the"
say "project to the one we created for Through the Cracks."
say ""

# Check if already authenticated
CURRENT_ACCOUNT=$(gcloud auth list --filter=status:ACTIVE --format="value(account)" 2>/dev/null || true)
if [[ -n "$CURRENT_ACCOUNT" ]]; then
  printf '  %s✓ Already authenticated as:%s %s\n' "$GREEN" "$RESET" "$CURRENT_ACCOUNT"
  say ""
  if ! confirm "Keep this account? (N to re-authenticate)"; then
    step "Opening browser for Google sign-in..."
    gcloud auth login --brief 2>&1
  fi
else
  step "Opening browser for Google sign-in..."
  gcloud auth login --brief 2>&1
fi

say ""

# Set the project
CURRENT_PROJECT=$(gcloud config get-value project 2>/dev/null || true)
if [[ -n "$CURRENT_PROJECT" ]]; then
  printf '  Current project: %s%s%s\n' "$BOLD" "$CURRENT_PROJECT" "$RESET"
  if confirm "Use this project?"; then
    GCP_PROJECT="$CURRENT_PROJECT"
  else
    ask GCP_PROJECT "Enter your GCP project ID:"
    gcloud config set project "$GCP_PROJECT" 2>&1
  fi
else
  say "Let's set the GCP project. You can find your project ID at:"
  open_url "https://console.cloud.google.com/home/dashboard"
  say ""
  ask GCP_PROJECT "Enter your GCP project ID:"
  gcloud config set project "$GCP_PROJECT" 2>&1
fi

write_env GCP_PROJECT_ID "$GCP_PROJECT"

say ""

# Set up Application Default Credentials for the Node.js BigQuery client
step "Setting up Application Default Credentials..."
say "This opens a browser window for you to authorize local applications"
say "to access your GCP project (including BigQuery)."
say ""
gcloud auth application-default login --quiet 2>&1 || {
  warn "ADC login did not complete — you may need to run this manually:"
  note "  gcloud auth application-default login"
}

say ""
printf '  %s✓ Authentication complete%s\n' "$GREEN" "$RESET"
pause "Press Enter to continue..."

# ── Stage 3: Enable BigQuery API ──────────────────────────────────────────
stage "Enable the BigQuery API"
say ""
say "Enabling the BigQuery API on your project..."
say ""

if gcloud services enable bigquery.googleapis.com 2>&1; then
  printf '  %s✓ BigQuery API enabled%s\n' "$GREEN" "$RESET"
else
  warn "Could not enable the API via CLI. Let's do it manually:"
  open_url "https://console.cloud.google.com/apis/library/bigquery.googleapis.com"
  step "Click the 'Enable' button on that page."
  pause "Press Enter once BigQuery API is enabled..."
fi

say ""
pause "Press Enter to continue..."

# ── Stage 4: Create BigQuery dataset ──────────────────────────────────────
stage "Create BigQuery dataset and tables"
say ""
say "Creating the 'through_the_cracks' dataset in BigQuery..."
say ""

BQ_DATASET="through_the_cracks"

# Create dataset (ignore error if it exists)
if bq mk --dataset --location=US "${GCP_PROJECT}:${BQ_DATASET}" 2>/dev/null; then
  printf '  %s✓ Created dataset:%s %s\n' "$GREEN" "$RESET" "$BQ_DATASET"
else
  note "Dataset '$BQ_DATASET' may already exist — that's fine."
fi

say ""
step "Creating 'episodes' table..."

bq mk --table "${GCP_PROJECT}:${BQ_DATASET}.episodes" \
  id:STRING,title:STRING,air_date:DATE,day_of_week:STRING,episode_number:INTEGER,published_at:TIMESTAMP,url:STRING,song_count:INTEGER,ingested_at:TIMESTAMP \
  2>/dev/null && printf '  %s✓ Created table: episodes%s\n' "$GREEN" "$RESET" \
  || note "Table 'episodes' may already exist — that's fine."

step "Creating 'song_plays' table..."

bq mk --table "${GCP_PROJECT}:${BQ_DATASET}.song_plays" \
  id:STRING,episode_id:STRING,air_date:DATE,position:INTEGER,artist:STRING,song_title:STRING,album:STRING,raw_line:STRING,ingested_at:TIMESTAMP \
  2>/dev/null && printf '  %s✓ Created table: song_plays%s\n' "$GREEN" "$RESET" \
  || note "Table 'song_plays' may already exist — that's fine."

write_env BQ_DATASET "$BQ_DATASET"

say ""
pause "Press Enter to continue..."

# ── Stage 5: Verify ──────────────────────────────────────────────────────
stage "Verify BigQuery setup"
say ""
say "Running a quick test query to verify everything works..."
say ""

RESULT=$(bq query --use_legacy_sql=false --format=prettyjson \
  "SELECT 'Through the Cracks is ready!' AS status, CURRENT_TIMESTAMP() AS checked_at" 2>/dev/null || echo "FAILED")

if [[ "$RESULT" != "FAILED" ]]; then
  printf '  %s✓ BigQuery is working!%s\n' "$GREEN" "$RESET"
  say ""
  echo "$RESULT" | head -10 | while IFS= read -r line; do note "$line"; done
else
  printf '  %s✗ BigQuery test query failed.%s\n' "$RED" "$RESET"
  warn "Check that the BigQuery API is enabled and you have permissions."
fi

say ""

# Summary
note "BigQuery is configured with:"
note "  Project:  $GCP_PROJECT"
note "  Dataset:  $BQ_DATASET"
note "  Tables:   episodes, song_plays"
say ""
pause "Press Enter to finish..."

# ──────────────────────────────────────────────────────────────────────────

finish
