#!/usr/bin/env bash
#
# Through the Cracks — Google Cloud / Blogger API key setup wizard
# Generated by the /wizard skill.
#
# Walks you through creating a Google Cloud project, enabling the Blogger API,
# and generating an API key. Takes about 5 minutes.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

banner "Through the Cracks — Blogger API Key Setup"

# ── Stage 1: Create / select a Google Cloud project ───────────────────────
stage "Create or select a Google Cloud project"
say ""
say "We need a Google Cloud project to hold your API key."
say "If you already have a project you'd like to use, you can select it."
say "Otherwise, create a new one (suggested name: 'through-the-cracks')."
say ""
open_url "https://console.cloud.google.com/projectcreate"
say ""
step "Click 'Create Project' (or if you have one, go to the project selector"
step "at the top of the page and select your existing project)."
step "Give it a name like 'through-the-cracks'."
step "Wait for the project to be created (~10 seconds)."
say ""
pause "Press Enter once your project is created and selected..."

# ── Stage 2: Enable the Blogger API ───────────────────────────────────────
stage "Enable the Blogger API"
say ""
say "Now we'll enable the Blogger API v3 on your project."
say ""
open_url "https://console.cloud.google.com/apis/library/blogger.googleapis.com"
say ""
step "You should see the 'Blogger API' page."
step "Click the blue 'Enable' button."
step "Wait for it to activate (~5 seconds)."
say ""
note "If it says 'API enabled' or 'Manage', it's already enabled — skip ahead."
say ""
pause "Press Enter once the Blogger API is enabled..."

# ── Stage 3: Create an API key ────────────────────────────────────────────
stage "Create an API key"
say ""
say "Now we'll create an API key for accessing the Blogger API."
say ""
open_url "https://console.cloud.google.com/apis/credentials"
say ""
step "Click '+ CREATE CREDENTIALS' at the top of the page."
step "Select 'API key' from the dropdown."
step "A dialog will appear with your new API key — copy it."
say ""
warn "You can optionally restrict this key to only the Blogger API"
warn "for security: click 'Edit API key', then under 'API restrictions',"
warn "select 'Restrict key' and choose 'Blogger API v3'."
say ""
ask_secret BLOGGER_API_KEY "Paste your API key here:"
write_env BLOGGER_API_KEY "$BLOGGER_API_KEY"
say ""

# ── Stage 4: Verify the key works ────────────────────────────────────────
stage "Verify the API key works"
say ""
say "Let's test that your API key can reach Ed Dirmeyer's blog."
say ""
note "Blog ID: 3469042462299367694"
say ""

# The blog ID is known — hardcode it
BLOG_ID="3469042462299367694"
write_env BLOGGER_BLOG_ID "$BLOG_ID"

step "Testing API connection..."
say ""

HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
  "https://www.googleapis.com/blogger/v3/blogs/${BLOG_ID}?key=${BLOGGER_API_KEY}" 2>/dev/null || echo "000")

if [[ "$HTTP_CODE" == "200" ]]; then
  printf '  %s✓ API key works!%s Connected to the Through the Cracks blog.\n' "$GREEN" "$RESET"
  say ""

  # Fetch the blog name to confirm
  BLOG_RESPONSE=$(curl -s \
    "https://www.googleapis.com/blogger/v3/blogs/${BLOG_ID}?key=${BLOGGER_API_KEY}" 2>/dev/null || echo "{}")

  BLOG_NAME=$(echo "$BLOG_RESPONSE" | grep -o '"name":"[^"]*"' | head -1 | sed 's/"name":"//;s/"$//')
  TOTAL_POSTS=$(echo "$BLOG_RESPONSE" | grep -o '"totalItems":[0-9]*' | head -1 | sed 's/"totalItems"://')

  [[ -n "$BLOG_NAME" ]]  && note "Blog name: $BLOG_NAME"
  [[ -n "$TOTAL_POSTS" ]] && note "Total posts: $TOTAL_POSTS"
else
  printf '  %s✗ Got HTTP %s — check your API key and try again.%s\n' "$RED" "$HTTP_CODE" "$RESET"
  warn "Common issues:"
  warn "  - API key was copied incorrectly (extra spaces?)"
  warn "  - Blogger API isn't enabled on your project"
  warn "  - API key has restrictions that block the Blogger API"
  say ""
  warn "You can re-run this wizard to try again."
fi

say ""
pause "Press Enter to finish..."

# ──────────────────────────────────────────────────────────────────────────

finish
